# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36ebd5f3ccabafc0bc472cc5207ffdc80de242f5e8f6646a2aec38b6d5760d8772ec439fb9c5ed93213284492de40b6d704ed8835e22d8c63eda811eb0946063

test:
  secret_key_base: 2578254fa3a18de3eea2a3f665c144798158a4f17442562684ac4384bed39a34efb1b95b3fc96826ab9999536e577d6b36ee84b78a9bb23168dc93089417355a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
